import torch

# ── Model ─────────────────────────────────────────────────────────────────────
MODEL_ID = "microsoft/Phi-3-mini-128k-instruct"


def get_device():
    if torch.backends.mps.is_available():
        return "mps"
    elif torch.cuda.is_available():
        return "cuda"
    return "cpu"


DEVICE = get_device()

# ── LLM generation ────────────────────────────────────────────────────────────
MAX_NEW_TOKENS = 512
TEMPERATURE    = 0.7
DO_SAMPLE      = True

# ── Backend ───────────────────────────────────────────────────────────────────
BACKEND      = "ollama"
OLLAMA_MODEL = "phi3:mini"

# ── Embedding ─────────────────────────────────────────────────────────────────
# Lightweight model (~80 MB); runs locally on CPU/MPS without a GPU.
EMBEDDING_MODEL = "all-MiniLM-L6-v2"

# ── Recommender paths ─────────────────────────────────────────────────────────
# Drop JSON files here to extend the catalog.
CATALOG_DIR = "./catalog"

# Generated by catalog_builder.py — do not edit manually.
CATALOG_INDEX_DIR = "./catalog_index"

# ── Hybrid similarity weights (must sum to 1.0) ───────────────────────────────
# Structured: numeric fields (deductibles, copays, coinsurance, visit limits …)
# Semantic:   sentence embedding of a readable plan text summary
STRUCTURED_WEIGHT = 0.5
SEMANTIC_WEIGHT   = 0.5

# How many results to return by default.
TOP_K = 5
